import type { Metadata } from "next";
import "./globals.css";
import { Baskervville, Poppins } from 'next/font/google'
import Footer from "@/components/footer";

const baskervville = Baskervville({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-baskervville',
})

const poppins = Poppins({ 
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${poppins.variable} ${baskervville.variable} antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
